### ISSUE TITLE
Questions about the efficiency of this implementation

### ISSUE THREAD

**Issue by yunmingxiao** [desire2020/SRU-tensorflow#2]
I tried this code but I couldn't find it more efficient than traditional LSTM model (using tensorflow.contrib.rnn.BasicLSTMCell). 
I suppose it is not likely to calculate the next f, r, and c without waiting for the result of the cuurent_hidden_state. And if so, why would this SRU run faster than LSTM? 
Or something I've done was wrong?

**Comment by oiwio** [comment]
@Awdrtgg This is just a naive implementation of SRU. If you review that paper, you will find a lot of efficient trick, such as calculate f,r at the same. And 

> Optimizing SRU is similar to but much easier than the cuDNN LSTM (Appleyard et al., 2016). Our RNN formulation permits two optimizations. First, the matrix multiplications across all time steps can be batched, which can significantly improve the computation intensity and hence GPU utilization. Second, all element-wise operations of the sequence can be fused (compiled) into one kernel function and be parallelized across hidden dimensions. Without the fusion, operations such as addition + and sigmoid activation σ() would invoke a separate function call. This brings additional kernel launching latency and also adds data moving cost.

So here is just a naive implementation of SRU. If you want to use it in your program, you need to use the official version or implement a tensorflow version by yourself.

**Comment by desire2020** [comment]
Hello, thanks for paying attention to this work. To my knowledge, if you simply apply this part of code to your project with the official implementation of RNN by TensorFlow, tf fails to calculate the correct dependency across all time steps. My advice is, if you really want to utilize the performance superiority of SRU, you'd better avoid using the official implementation of RNN. Instead, you can implement an RNN by yourself, where you can actually do some mentioned optimizations such as batched matrix multiplications.
Good luck, have fun!

Yours sincerely,
desire2020.
